[package]
name = "symphony-interfaces"
version.workspace = true
edition.workspace = true

[dependencies]
cosmwasm-schema = { workspace = true }
cw-utils = { workspace = true }
cosmwasm-std = { workspace = true }
cw-ownable = { workspace = true }
cw-controllers = { version = "2.0.0" }